---
title: "CombinedMarkdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}    
library(dplyr)
library(tidyr)
library(ggplot2)
library(Amelia)

#Read in files
g_data <- read.csv("general_data.csv")
ms_data <- read.csv("manager_survey_data.csv")
es_data <- read.csv("employee_survey_data.csv")
in_time <- read.csv("in_time.csv")
out_time <- read.csv("out_time.csv")
hours <- read.csv("Employee_Daily_Hours_Final.csv")
names(hours)[1] <- "EmployeeID"
```

```{r}
Master_Data <- merge(g_data,es_data,by = 'EmployeeID',all = F)
Master_Data <- merge(Master_Data,ms_data,by = 'EmployeeID',all = F)
Master_Data <- merge(Master_Data,hours,by = 'EmployeeID',all = F)

##MISSING DATA
#Missing Data Map
missmap(Master_Data,y.at=c(1),y.labels = c(''),col=c('yellow','black'))
#Omit NA data from dataframe since very little NA
Master_Data <- na.omit(Master_Data)
#Re-run missing data map
missmap(Master_Data,y.at=c(1),y.labels = c(''),col=c('yellow','black'))
#No more missing values
```

```{r}
##EXPLORATORY DATA ANALYSIS
ggplot(Master_Data,aes(MonthlyIncome)) + 
    geom_histogram(aes(fill=Attrition),color='black',binwidth=10000) + theme_bw()
#Higher levels of attrition at lower income levels
```

```{r}
ggplot(Master_Data,aes(WorkLifeBalance)) +
  geom_bar(aes(fill = Attrition),color = 'black') +
  theme_bw()
#WorkLifeBalance: 1-Bad,2-Good,3-Better,4-Best
#Those with 'better' work life balance seem to leave more - no pattern
```

```{r}
ggplot(Master_Data,aes(DistanceFromHome)) + 
  geom_histogram(aes(fill=Attrition),color='black',binwidth=2) + theme_bw()
#People who live close to work seem to leave the company more often
```

```{r}
ggplot(Master_Data,aes(JobRole)) +
  geom_bar(aes(fill = Attrition),color = 'black') +
  theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
#There seems to be higher attrition among the Lab Technicians, Research Scientists, and Sales Execs
#But theres also more of these 3 job roles - non-conclusive
```

```{r}
ggplot(Master_Data,aes(JobLevel)) +
  geom_bar(aes(fill = Attrition),color = 'black') +
  theme_bw()
#People at the lower job levels seem to leave more often
```

```{r}
##CLEAN DATA

#Remove columns we dont need in our analysis
#Master_Data <- select(Master_Data,-EmployeeID,-EmployeeCount,-Over18,-StandardHours)
Master_Data$StandardHours <- NULL
Master_Data$Over18 <- NULL
Master_Data$EmployeeCount <- NULL
Master_Data$EmployeeID <- NULL
```


```{r}
##SPLIT DATA
library(caTools)

sample <- sample.split(Master_Data$Attrition,SplitRatio = 0.7)

#Training Data
train <- subset(Master_Data,sample==T)
#Testing Data
test <- subset(Master_Data,sample==F)
```

```{r}
##TRAIN THE LOGISTIC REGRESSION MODEL
logModel <- glm(Attrition ~., family = binomial('logit'),data = train)
summary(logModel)
```

```{r}
##PREDICTIONS
pred_probabilities <- predict(logModel,test,type = 'response')
pred_results <- ifelse(pred_probabilities>0.5,1,0)

#Convert Attrition column in test to 0s and 1s to compare to pred_results
test$AttritionClass <- ifelse(test$Attrition == 'Yes',1,0)

misClassError <- mean(pred_results != test$AttritionClass)
accuracy <- (1-misClassError)

cat("Misclassification error:", misClassError, "\n")
cat("Accuracy:", accuracy, "\n")
```

```{r}
library(glmnet)
testPredictions = predict(logModel, test)

trainMatrix <- model.matrix(Attrition ~ ., data = train)
testMatrix <- model.matrix(Attrition ~ ., data = test)
grid <- 10 ^ seq(4, -2, length = 100)
lasso <- glmnet(trainMatrix, train$Attrition, alpha = 1, lambda = grid, thresh = 1e-12, family = "binomial")
lassoCV <- cv.glmnet(trainMatrix, train$Attrition, alpha = 1, lambda = grid, thresh = 1e-12, family = "binomial")
lassoLambdaMin <- lassoCV$lambda.min
#lassoTestPredictions <- predict(lasso, s = lassoLambdaMin, newx = testMatrix)
predict(lasso, s = lassoLambdaMin, type = "coefficients")
```

```{r}
plot(lasso, xvar = "dev")
plot(lasso, xvar = "lambda")
```

```{r}
#new Logistic model
logModel2 <- glm(Attrition ~ Age + BusinessTravel + JobRole + MaritalStatus + NumCompaniesWorked + StockOptionLevel + TotalWorkingYears + TrainingTimesLastYear + YearsSinceLastPromotion + YearsWithCurrManager + EnvironmentSatisfaction + JobSatisfaction + WorkLifeBalance, family = binomial('logit'),data = train)

summary(logModel2)
```

```{r}
pred_probabilities2 <- predict(logModel2,test,type = 'response')
pred_results2 <- ifelse(pred_probabilities2>0.5,1,0)

#Convert Attrition column in test to 0s and 1s to compare to pred_results
test$AttritionClass <- ifelse(test$Attrition == 'Yes',1,0)

misClassError2 <- mean(pred_results2 != test$AttritionClass)
accuracy2 <- (1-misClassError2)

cat("Misclassification error:", misClassError2, "\n")
cat("Accuracy:", accuracy2, "\n")
```




```{r}
#Remove columns we dont need in our knn analysis
knnData <- Master_Data <- select(Master_Data,
                      -BusinessTravel,-Department,-DistanceFromHome,
                      -EducationField,-Gender,-JobRole,-MaritalStatus)
```

```{r}
#Target column
attrition <- knnData[,2]
#Scale data
scaled_knnData <- scale(knnData[,-2])
#Join scaled data with target column
final_data <- cbind(scaled_knnData,attrition)
```

```{r}
#Train/Test Split
test_index <- 3001:4300
test_data <- scaled_knnData[test_index,]
test_attrition <- attrition[test_index]

train_data <- scaled_knnData[-test_index,]
train_attrition <- attrition[-test_index]

#Building the KNN Model
library(class)
predicted_attrition <- knn(train_data,test_data,train_attrition,k=1)

#Misclassification error
misclass_error <- mean(test_attrition != predicted_attrition)
cat("Misclassification error:", misclass_error, "\n")

accuracy <- (1-misclass_error)
cat("Accuracy:", accuracy, "\n")

#######
#Choosing a k value

pred_attrition <- NULL
error_rate <- NULL

for (i in 1:50){
  pred_attrition <- knn(train_data,test_data,train_attrition,k=i)
  error_rate[i] <- mean(test_attrition != pred_attrition)
  cat("Error rate for k =", i, ":", error_rate[i], "\n")
}
#print(error_rate)

#Visualize K Elbow Method
k_values <- 1:50
error_df <- data.frame(error_rate,k_values)

ggplot(error_df,aes(k_values,error_rate)) +
  geom_point() + geom_line(lty = 'dotted',color = 'red')

```

